# Generated by Django 5.2.14 on 2026-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="painting",
            options={"ordering": ("title",)},
        ),
        migrations.RemoveField(
            model_name="painting",
            name="year",
        ),
        migrations.AddField(
            model_name="artist",
            name="birth_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="painting",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="painting",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1900, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="painting",
            name="year_created",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
