# Generated by Django 5.2.14 on 2026-05-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ("last_name",)},
        ),
        migrations.RemoveField(
            model_name="artist",
            name="pseudonym",
        ),
        migrations.RemoveField(
            model_name="painting",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="painting",
            name="writers",
        ),
        migrations.AddField(
            model_name="artist",
            name="birth_year",
            field=models.IntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="death_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="painting",
            name="artist",
            field=models.ForeignKey(
                default=1900,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paintings",
                to="museum.artist",
            ),
            preserve_default=False,
        ),
    ]
