# Generated by Django 5.2.14 on 2026-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0002_alter_painting_options_remove_painting_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="favorite_paintings",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="museum.painting"
            ),
        ),
    ]
