# Generated by Django 5.2.14 on 2026-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0003_artist_favorite_paintings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="painting",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
